"n""a""m""e"":"" ""J""a""v""a"" ""C""I"" ""w""i""t""h"" ""M""a""v""e""n"

"o""n"":"
" "" ""p""u""s""h"":"
" "" "" "" ""b""r""a""n""c""h""e""s"":"" ""m""a""s""t""e""r"
" "" ""p""u""l""l""_""r""e""q""u""e""s""t"":"
" "" "" "" ""b""r""a""n""c""h""e""s"":"" ""m""a""s""t""e""r"
" "" ""w""o""r""k""f""l""o""w""_""d""i""s""p""a""t""c""h"":"
" "" "" "" ""b""r""a""n""c""h""e""s"":"" ""["" ""$""d""e""f""a""u""l""t""-""b""r""a""n""c""h"" ""]"

"j""o""b""s"":"
" "" ""b""u""i""l""d"":"

" "" "" "" ""r""u""n""s""-""o""n"":"" ""u""b""u""n""t""u""-""l""a""t""e""s""t"

" "" "" "" ""s""t""e""p""s"":"
" "" "" "" ""-"" ""u""s""e""s"":"" ""a""c""t""i""o""n""s""/""c""h""e""c""k""o""u""t""@""v""2"
" "" "" "" ""-"" ""n""a""m""e"":"" ""S""e""t"" ""u""p"" ""J""D""K"" ""1""1"
" "" "" "" "" "" ""u""s""e""s"":"" ""a""c""t""i""o""n""s""/""s""e""t""u""p""-""j""a""v""a""@""v""2"
" "" "" "" "" "" ""w""i""t""h"":"
" "" "" "" "" "" "" "" ""j""a""v""a""-""v""e""r""s""i""o""n"":"" ""'""1""1""'"
" "" "" "" "" "" "" "" ""d""i""s""t""r""i""b""u""t""i""o""n"":"" ""'""a""d""o""p""t""'"
" "" "" "" ""-"" ""n""a""m""e"":"" ""B""u""i""l""d"" ""w""i""t""h"" ""M""a""v""e""n"
" "" "" "" "" "" ""r""u""n"":"" ""m""v""n"" ""-""B"" ""p""a""c""k""a""g""e"" ""-""-""f""i""l""e"" ""p""o""m"".""x""m""l"
